import type { SpliceTreeData } from '@splicetree/adapter-vue'

export const treeData: SpliceTreeData[] = [
  { id: 'tropical', title: 'Tropical Fruits' },
  { id: 'banana', title: 'Banana', parent: 'tropical' },
  { id: 'banana-small', title: 'Small Banana', parent: 'banana' },
  { id: 'banana-small-premium', title: 'Premium Small Banana', parent: 'banana-small' },
  { id: 'mango', title: 'Mango', parent: 'tropical' },
  { id: 'mango-tainong', title: 'Tainong Mango', parent: 'mango' },
  { id: 'mango-green', title: 'Green Mango', parent: 'mango' },
  { id: 'mango-green-sweet', title: 'Sweet Green Mango', parent: 'mango-green' },
  { id: 'pineapple', title: 'Pineapple', parent: 'tropical' },
  { id: 'pineapple-honey', title: 'Honey Pineapple', parent: 'pineapple' },
  { id: 'pineapple-honey-premium', title: 'Premium Honey Pineapple', parent: 'pineapple-honey' },
  { id: 'dragonfruit', title: 'Dragon Fruit', parent: 'tropical' },
  { id: 'dragonfruit-red', title: 'Red Dragon Fruit', parent: 'dragonfruit' },
  { id: 'dragonfruit-white', title: 'White Dragon Fruit', parent: 'dragonfruit' },
  { id: 'dragonfruit-red-premium', title: 'Premium Red Dragon Fruit', parent: 'dragonfruit-red' },
  { id: 'berries', title: 'Berries' },
  { id: 'strawberry', title: 'Strawberry', parent: 'berries' },
  { id: 'strawberry-cream', title: 'Cream Strawberry', parent: 'strawberry' },
  { id: 'strawberry-cream-supreme', title: 'Supreme Cream Strawberry', parent: 'strawberry-cream' },
  { id: 'blueberry', title: 'Blueberry', parent: 'berries' },
  { id: 'blueberry-wild', title: 'Wild Blueberry', parent: 'blueberry' },
  { id: 'blueberry-wild-premium', title: 'Premium Wild Blueberry', parent: 'blueberry-wild' },
  { id: 'raspberry', title: 'Raspberry', parent: 'berries' },
  { id: 'raspberry-red', title: 'Red Raspberry', parent: 'raspberry' },
  { id: 'raspberry-gold', title: 'Gold Raspberry', parent: 'raspberry' },
  { id: 'blackberry', title: 'Blackberry', parent: 'berries' },
  { id: 'blackberry-wild', title: 'Wild Blackberry', parent: 'blackberry' },
  { id: 'citrus', title: 'Citrus Fruits' },
  { id: 'orange', title: 'Orange', parent: 'citrus' },
  { id: 'orange-navel', title: 'Navel Orange', parent: 'orange' },
  { id: 'orange-blood', title: 'Blood Orange', parent: 'orange' },
  { id: 'orange-blood-premium', title: 'Premium Blood Orange', parent: 'orange-blood' },
  { id: 'lemon', title: 'Lemon', parent: 'citrus' },
  { id: 'lemon-meyer', title: 'Meyer Lemon', parent: 'lemon' },
  { id: 'lemon-meyer-sweet', title: 'Sweet Meyer Lemon', parent: 'lemon-meyer' },
  { id: 'lime', title: 'Lime', parent: 'citrus' },
  { id: 'lime-key', title: 'Key Lime', parent: 'lime' },
  { id: 'lime-key-premium', title: 'Premium Key Lime', parent: 'lime-key' },
  { id: 'stone-fruits', title: 'Stone Fruits' },
  { id: 'peach', title: 'Peach', parent: 'stone-fruits' },
  { id: 'peach-white', title: 'White Peach', parent: 'peach' },
  { id: 'peach-yellow', title: 'Yellow Peach', parent: 'peach' },
  { id: 'peach-white-premium', title: 'Premium White Peach', parent: 'peach-white' },
  { id: 'plum', title: 'Plum', parent: 'stone-fruits' },
  { id: 'plum-red', title: 'Red Plum', parent: 'plum' },
  { id: 'plum-black', title: 'Black Plum', parent: 'plum' },
  { id: 'cherry', title: 'Cherry', parent: 'stone-fruits' },
  { id: 'cherry-rainier', title: 'Rainier Cherry', parent: 'cherry' },
  { id: 'cherry-rainier-premium', title: 'Premium Rainier Cherry', parent: 'cherry-rainier' },
  { id: 'melon', title: 'Melons' },
  { id: 'watermelon', title: 'Watermelon', parent: 'melon' },
  { id: 'watermelon-mini', title: 'Mini Watermelon', parent: 'watermelon' },
  { id: 'watermelon-mini-sweet', title: 'Sweet Mini Watermelon', parent: 'watermelon-mini' },
  { id: 'cantaloupe', title: 'Cantaloupe', parent: 'melon' },
  { id: 'cantaloupe-honey', title: 'Honey Cantaloupe', parent: 'cantaloupe' },
]
